/*
 * GENERATED by firmware/tools/gen_filter_coeffs.py -- do not edit by hand.
 *
 * Generated : 2026-09-07
 * scipy     : 1.17.1
 * Bands     : heart 20-200 Hz, lung 150-1000 Hz
 *             (imported from src/baseline/common.py -- change them there, then rerun this tool)
 * Design    : Butterworth order 4 bandpass @ 4000 Hz,
 *             Butterworth order 8 lowpass @ 1400 Hz for 16000 -> 4000 Hz decimation
 *
 * Layout is scipy's second-order sections with a0 divided out:
 *   {b0, b1, b2, a1, a2} per section, y[n] = b0*x[n] + b1*x[n-1] + b2*x[n-2] - a1*y[n-1] - a2*y[n-2]
 * which is exactly what ESP-DSP's dsps_biquad_f32 expects. The CMSIS-DSP
 * backend negates a1/a2 at init (see hls_filter.c) because CMSIS uses the
 * opposite denominator sign.
 */
#ifndef HLS_FILTER_COEFFS_H
#define HLS_FILTER_COEFFS_H

#define HLS_BASELINE_SR_HZ 4000u
#define HLS_MIC_SR_HZ      16000u
#define HLS_DECIM_FACTOR   4u

#define HLS_HEART_LOW_HZ   20.0f
#define HLS_HEART_HIGH_HZ  200.0f
#define HLS_LUNG_LOW_HZ    150.0f
#define HLS_LUNG_HIGH_HZ   1000.0f

/* heart bandpass 20-200 Hz @ 4000 Hz */
#define HLS_HEART_SECTIONS 4u
static const float HLS_HEART_SOS[HLS_HEART_SECTIONS * 5] = {
     2.831443306e-04f,  5.662886611e-04f,  2.831443306e-04f, -1.574851046e+00f,  6.304737446e-01f,
     1.000000000e+00f,  2.000000000e+00f,  1.000000000e+00f, -1.738046774e+00f,  8.237521956e-01f,
     1.000000000e+00f, -2.000000000e+00f,  1.000000000e+00f, -1.934638874e+00f,  9.360197071e-01f,
     1.000000000e+00f, -2.000000000e+00f,  1.000000000e+00f, -1.978727562e+00f,  9.797459778e-01f,
};

/* lung bandpass 150-1000 Hz @ 4000 Hz */
#define HLS_LUNG_SECTIONS 4u
static const float HLS_LUNG_SOS[HLS_LUNG_SECTIONS * 5] = {
     5.639757835e-02f,  1.127951567e-01f,  5.639757835e-02f, -2.354829826e-01f,  8.875237510e-02f,
     1.000000000e+00f,  2.000000000e+00f,  1.000000000e+00f, -3.549922927e-02f,  5.300596613e-01f,
     1.000000000e+00f, -2.000000000e+00f,  1.000000000e+00f, -1.535077449e+00f,  6.033080292e-01f,
     1.000000000e+00f, -2.000000000e+00f,  1.000000000e+00f, -1.809422548e+00f,  8.633164668e-01f,
};

/* anti-alias lowpass 1400 Hz @ 16000 Hz, decimate by 4 */
#define HLS_DECIM_SECTIONS 4u
static const float HLS_DECIM_SOS[HLS_DECIM_SECTIONS * 5] = {
     9.554077873e-06f,  1.910815575e-05f,  9.554077873e-06f, -1.127488705e+00f,  3.223499814e-01f,
     1.000000000e+00f,  2.000000000e+00f,  1.000000000e+00f, -1.188811196e+00f,  3.942706973e-01f,
     1.000000000e+00f,  2.000000000e+00f,  1.000000000e+00f, -1.321631106e+00f,  5.500455663e-01f,
     1.000000000e+00f,  2.000000000e+00f,  1.000000000e+00f, -1.547533418e+00f,  8.149900538e-01f,
};

#endif /* HLS_FILTER_COEFFS_H */
